[project]
site_name = "Convax"
site_url = "https://convax.tedpinkerton.ca/"
repo_url = "https://github.com/RunnersNum40/convax"
repo_name = "RunnersNum40/convax"
edit_uri = "edit/main/docs"
site_description = "Convex set manipulation library in JAX with Equinox"
site_author = "Theodore Pinkerton"
copyright = "&copy; 2026 Theodore Pinkerton"
strict = true
extra_javascript = [
  "javascripts/mathjax.js",
  "https://unpkg.com/mathjax@3.2.2/es5/tex-mml-chtml.js",
]
extra_css = ["stylesheets/extra.css"]

[project.validation]
invalid_links = true
invalid_link_anchors = true

[project.theme]
variant = "modern"
language = "en"
features = [
  "content.code.copy",
  "content.code.select",
  "content.code.annotate",
  "content.footnote.tooltips",
  "content.tabs.link",
  "content.tooltips",
  "header.autohide",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.instant.progress",
  "navigation.path",
  "navigation.sections",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
  "toc.follow",
]

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[project.theme.icon]
logo = "lucide/book-x"
repo = "fontawesome/brands/github"

[project.plugins.mkdocstrings.handlers.python]
inventories = [
  "https://docs.python.org/3/objects.inv",
  "https://docs.jax.dev/en/latest/objects.inv",
  "https://docs.kidger.site/equinox/objects.inv",
  "https://docs.kidger.site/jaxtyping/objects.inv",
]
paths = ["src"]

[project.plugins.mkdocstrings.handlers.python.options]
annotations_path = "brief"
docstring_style = "google"
filters = "public"
members_order = "source"
separate_signature = true
show_root_full_path = false
show_root_heading = true
show_root_toc_entry = false
show_signature_annotations = true
show_signature_type_parameters = true
show_source = false
show_symbol_type_heading = true
show_symbol_type_toc = true
signature_crossrefs = true
type_parameter_headings = true
